//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFormsClient.ProductReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductReference.IProduct")]
    public interface IProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Create", ReplyAction="http://tempuri.org/IProduct/CreateResponse")]
        bool Create(string name, string description, int category, int stock, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Create", ReplyAction="http://tempuri.org/IProduct/CreateResponse")]
        System.Threading.Tasks.Task<bool> CreateAsync(string name, string description, int category, int stock, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Update", ReplyAction="http://tempuri.org/IProduct/UpdateResponse")]
        bool Update(string name, string newName, string newDescription, int newCategory, int newStock, decimal newPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Update", ReplyAction="http://tempuri.org/IProduct/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(string name, string newName, string newDescription, int newCategory, int newStock, decimal newPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Delete", ReplyAction="http://tempuri.org/IProduct/DeleteResponse")]
        bool Delete(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Delete", ReplyAction="http://tempuri.org/IProduct/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/ReadAllAsList", ReplyAction="http://tempuri.org/IProduct/ReadAllAsListResponse")]
        string[] ReadAllAsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/ReadAllAsList", ReplyAction="http://tempuri.org/IProduct/ReadAllAsListResponse")]
        System.Threading.Tasks.Task<string[]> ReadAllAsListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductDetails", ReplyAction="http://tempuri.org/IProduct/GetProductDetailsResponse")]
        string[] GetProductDetails(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/GetProductDetails", ReplyAction="http://tempuri.org/IProduct/GetProductDetailsResponse")]
        System.Threading.Tasks.Task<string[]> GetProductDetailsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Restock", ReplyAction="http://tempuri.org/IProduct/RestockResponse")]
        bool Restock(string name, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProduct/Restock", ReplyAction="http://tempuri.org/IProduct/RestockResponse")]
        System.Threading.Tasks.Task<bool> RestockAsync(string name, int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductChannel : ShopFormsClient.ProductReference.IProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductClient : System.ServiceModel.ClientBase<ShopFormsClient.ProductReference.IProduct>, ShopFormsClient.ProductReference.IProduct {
        
        public ProductClient() {
        }
        
        public ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Create(string name, string description, int category, int stock, decimal price) {
            return base.Channel.Create(name, description, category, stock, price);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAsync(string name, string description, int category, int stock, decimal price) {
            return base.Channel.CreateAsync(name, description, category, stock, price);
        }
        
        public bool Update(string name, string newName, string newDescription, int newCategory, int newStock, decimal newPrice) {
            return base.Channel.Update(name, newName, newDescription, newCategory, newStock, newPrice);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(string name, string newName, string newDescription, int newCategory, int newStock, decimal newPrice) {
            return base.Channel.UpdateAsync(name, newName, newDescription, newCategory, newStock, newPrice);
        }
        
        public bool Delete(string name) {
            return base.Channel.Delete(name);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(string name) {
            return base.Channel.DeleteAsync(name);
        }
        
        public string[] ReadAllAsList() {
            return base.Channel.ReadAllAsList();
        }
        
        public System.Threading.Tasks.Task<string[]> ReadAllAsListAsync() {
            return base.Channel.ReadAllAsListAsync();
        }
        
        public string[] GetProductDetails(string name) {
            return base.Channel.GetProductDetails(name);
        }
        
        public System.Threading.Tasks.Task<string[]> GetProductDetailsAsync(string name) {
            return base.Channel.GetProductDetailsAsync(name);
        }
        
        public bool Restock(string name, int quantity) {
            return base.Channel.Restock(name, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> RestockAsync(string name, int quantity) {
            return base.Channel.RestockAsync(name, quantity);
        }
    }
}
