//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopFormsClient.CategoryReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CategoryReference.ICategory")]
    public interface ICategory {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/CreateCategory", ReplyAction="http://tempuri.org/ICategory/CreateCategoryResponse")]
        bool CreateCategory(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/CreateCategory", ReplyAction="http://tempuri.org/ICategory/CreateCategoryResponse")]
        System.Threading.Tasks.Task<bool> CreateCategoryAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/ReadCategory", ReplyAction="http://tempuri.org/ICategory/ReadCategoryResponse")]
        void ReadCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/ReadCategory", ReplyAction="http://tempuri.org/ICategory/ReadCategoryResponse")]
        System.Threading.Tasks.Task ReadCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/UpdateCategory", ReplyAction="http://tempuri.org/ICategory/UpdateCategoryResponse")]
        bool UpdateCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/UpdateCategory", ReplyAction="http://tempuri.org/ICategory/UpdateCategoryResponse")]
        System.Threading.Tasks.Task<bool> UpdateCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/DeleteCategory", ReplyAction="http://tempuri.org/ICategory/DeleteCategoryResponse")]
        bool DeleteCategory(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/DeleteCategory", ReplyAction="http://tempuri.org/ICategory/DeleteCategoryResponse")]
        System.Threading.Tasks.Task<bool> DeleteCategoryAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/GetCategoriesAsList", ReplyAction="http://tempuri.org/ICategory/GetCategoriesAsListResponse")]
        string[] GetCategoriesAsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategory/GetCategoriesAsList", ReplyAction="http://tempuri.org/ICategory/GetCategoriesAsListResponse")]
        System.Threading.Tasks.Task<string[]> GetCategoriesAsListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICategoryChannel : ShopFormsClient.CategoryReference.ICategory, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CategoryClient : System.ServiceModel.ClientBase<ShopFormsClient.CategoryReference.ICategory>, ShopFormsClient.CategoryReference.ICategory {
        
        public CategoryClient() {
        }
        
        public CategoryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateCategory(string name) {
            return base.Channel.CreateCategory(name);
        }
        
        public System.Threading.Tasks.Task<bool> CreateCategoryAsync(string name) {
            return base.Channel.CreateCategoryAsync(name);
        }
        
        public void ReadCategory(int id) {
            base.Channel.ReadCategory(id);
        }
        
        public System.Threading.Tasks.Task ReadCategoryAsync(int id) {
            return base.Channel.ReadCategoryAsync(id);
        }
        
        public bool UpdateCategory(int id) {
            return base.Channel.UpdateCategory(id);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCategoryAsync(int id) {
            return base.Channel.UpdateCategoryAsync(id);
        }
        
        public bool DeleteCategory(string name) {
            return base.Channel.DeleteCategory(name);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteCategoryAsync(string name) {
            return base.Channel.DeleteCategoryAsync(name);
        }
        
        public string[] GetCategoriesAsList() {
            return base.Channel.GetCategoriesAsList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCategoriesAsListAsync() {
            return base.Channel.GetCategoriesAsListAsync();
        }
    }
}
